#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES: deploy svoboda.page to Cloudflare and set up its services (#4).
# Run from the branch of the PR that added this script:
#   ./scripts/setup-cloudflare.sh
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=9

cd "$(git rev-parse --show-toplevel)"
# The Turnstile site key is public and the build needs it, so it goes to a
# committed file that Vite loads in production builds, not to .env.
ENV_FILE=".env.production"

DASH="https://dash.cloudflare.com/?to=/:account"
WORKER="svoboda-page" # must match "name" in wrangler.jsonc
DOMAIN="svoboda.page"
WORKER_SECRETS=() # Worker secrets set this run

# put_worker_secret NAME VALUE stores a secret on the Worker through
# Wrangler, so it never touches a file in the repo.
put_worker_secret() {
  local name="$1" value="$2"
  if printf '%s' "$value" | npx wrangler secret put "$name" >/dev/null 2>&1; then
    WORKER_SECRETS+=("$name")
    printf '  %s✓ uloženo%s tajemství %s ve Workeru %s\n' "$GREEN" "$RESET" "$name" "$WORKER"
  else
    SKIPPED+=("Worker secret $name (npx wrangler secret put $name)")
    warn "tajemství $name se nepodařilo uložit; spusť později: npx wrangler secret put $name"
  fi
}

# http_status URL prints the HTTP status code of URL without following
# redirects, or 000 when the request fails.
http_status() {
  curl -s -o /dev/null -w '%{http_code}' --max-time 10 "$1" || true
}

# wait_for_ok URL polls URL for up to five minutes until it answers 200.
wait_for_ok() {
  local url="$1" i
  for i in $(seq 1 30); do
    if [[ "$(http_status "$url")" == "200" ]]; then
      printf '  %s✓ %s odpovídá%s\n' "$GREEN" "$url" "$RESET"
      return 0
    fi
    note "čekám na $url ($i/30)…"
    sleep 10
  done
  return 1
}

for cmd in git gh npx curl; do
  command -v "$cmd" >/dev/null 2>&1 || { printf '%s chybí v systému, nainstaluj ho a spusť wizard znovu.\n' "$cmd"; exit 1; }
done

banner "Nasazení svoboda.page na Cloudflare"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Přihlášení Wrangleru do Cloudflare"
say "Wrangler je nástroj Cloudflare pro příkazovou řádku (máme ho v projektu)."
say "Wizard ho použije k uložení tajných hodnot přímo do Workeru, aby nikdy"
say "nebyly v repu. K tomu se musí jednou přihlásit k tvému účtu."
echo
if npx wrangler whoami 2>/dev/null | grep -q "You are logged in"; then
  printf '  %s✓ Wrangler už je přihlášený%s\n' "$GREEN" "$RESET"
else
  step "Otevře se prohlížeč. Přihlas se do Cloudflare a klikni na Allow."
  pause "Enter spustí přihlášení…"
  npx wrangler login
fi
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "DNS: uvolnit $DOMAIN a www.$DOMAIN"
say "DNS záznamy říkají, kam doména vede. Worker si po spuštění vytvoří"
say "vlastní záznamy pro $DOMAIN i www.$DOMAIN. Když tam už nějaký A, AAAA"
say "nebo CNAME záznam je (třeba ze staré stránky), nasazení selže."
echo
open_url "$DASH/:zone/dns/records"
step "Pokud se zeptá na doménu, vyber $DOMAIN."
step "Najdi záznamy typu A, AAAA nebo CNAME s názvem $DOMAIN (nebo @) a www."
step "Pokud nějaké jsou, smaž je (⋯ / Edit → Delete)."
note "Záznamy MX a TXT nech být, ty patří k e-mailu."
warn "Smazáním přestane fungovat to, na co doména vede teď. Na webu, který"
warn "na doméně případně běží, by měl být výpadek jen do konce tohoto wizardu."
pause "Hotovo (nebo tam nic nebylo)? Enter…"

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Worker napojený na GitHub"
say "Worker je program, který na serverech Cloudflare obsluhuje web."
say "Napojíme ho na GitHub: každý push do master se sám sestaví a nasadí,"
say "každý pull request dostane vlastní náhledovou adresu (preview)."
echo
open_url "$DASH/workers-and-pages"
step "Create application → u Import a repository klikni Get started."
step "Připoj GitHub účet. V instalaci aplikace Cloudflare zvol Only select"
note "  repositories → svoboda.page (Cloudflare uvidí jen toto repo)."
step "Vyber repo stansvoboda/svoboda.page."
step "Project name: přesně $WORKER (jinak build selže, musí sedět s wrangler.jsonc)."
step "Build command: npm run build"
step "Deploy command: npx wrangler deploy"
step "Save and Deploy. Kdyby nabízel placený plán, zůstaň na Free."
pause "Hotovo? Enter…"
echo
say "Teď nastavení buildu:"
step "V Workeru $WORKER otevři Settings → Build."
step "Git branch (produkční větev) nastav na master, pokud tam je main."
step "V Branch control zaškrtni Enable Preview Builds."
note "  Preview command nech výchozí (npx wrangler preview)."
step "Počkej, až první build v záložce Deployments doběhne (pár minut)."
pause "Build doběhl? Enter…"
echo
step "V Settings → Domains & Routes najdi adresu ve tvaru $WORKER.<něco>.workers.dev."
ask WORKERS_DEV_HOST "Vlož tu adresu (bez https://):"
WORKERS_DEV_HOST="${WORKERS_DEV_HOST#https://}"
WORKERS_DEV_HOST="${WORKERS_DEV_HOST%%/*}"
WORKERS_SUBDOMAIN="${WORKERS_DEV_HOST#"$WORKER".}"
if wait_for_ok "https://$WORKERS_DEV_HOST/en"; then
  say "Web běží na Cloudflare. Doménu připojíme na konci."
else
  warn "https://$WORKERS_DEV_HOST/en zatím neodpovídá. Zkontroluj build v Deployments."
  SKIPPED+=("ověřit, že https://$WORKERS_DEV_HOST/en běží")
fi
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Email Routing: tvoje schránka"
say "Kontaktní formulář pošle zprávu e-mailem do tvé osobní schránky."
say "Cloudflare umí posílat jen na adresy, které jsi ověřil. To je zdarma."
echo
open_url "$DASH/:zone/email/routing"
step "Pokud se zeptá na doménu, vyber $DOMAIN."
step "Zapni Email Routing (Get started / Enable). Nech ho přidat navržené"
note "  DNS záznamy MX a TXT a potvrď je."
step "V Destination addresses klikni Add destination address a zadej svou"
note "  osobní adresu. Přijde ti mail s odkazem, klikni na něj."
step "Počkej, až u adresy bude stav Verified."
echo
ask CONTACT_TO "Adresa schránky, kam má formulář posílat:"
note "Adresa se uloží jen jako tajemství Workeru, v (veřejném) repu nebude."
put_worker_secret CONTACT_TO "$CONTACT_TO"
if ! confirm "Je adresa v Cloudflare ve stavu Verified?"; then
  SKIPPED+=("ověřit $CONTACT_TO v Email Routing → Destination addresses")
fi
echo
say "Web ukazuje veřejnou adresu standa@$DOMAIN (když formulář selže)."
say "Cloudflare ji přepošle do tvé schránky, takže osobní adresa zůstane skrytá."
step "V Routing rules klikni Create address."
step "Custom address: standa. Action: Send to an email. Destination: $CONTACT_TO."
step "Save."
if ! confirm "Je pravidlo pro standa@$DOMAIN aktivní?"; then
  SKIPPED+=("pravidlo standa@$DOMAIN → $CONTACT_TO v Email Routing → Routing rules")
fi
pause

# ── 5 ─────────────────────────────────────────────────────────────────────
stage "Turnstile: ochrana formuláře proti spamu"
say "Turnstile je náhrada za CAPTCHA: ve stránce ověří, že formulář"
say "vyplňuje člověk, a server pak to ověření zkontroluje tajným klíčem."
echo
open_url "$DASH/turnstile"
step "Add widget."
step "Widget name: svoboda.page contact"
step "Hostname management: přidej $DOMAIN a $WORKERS_SUBDOMAIN"
note "  (hostname platí i pro subdomény, takže formulář půjde i v náhledech PR)."
step "Widget mode: Managed. Pre-clearance: No."
step "Create. Zobrazí se Site Key a Secret Key."
echo
ask TURNSTILE_SITE_KEY "Vlož Site Key (veřejný):"
write_env VITE_TURNSTILE_SITE_KEY "$TURNSTILE_SITE_KEY"
ask_secret TURNSTILE_SECRET_KEY "Vlož Secret Key (nezobrazí se):"
put_worker_secret TURNSTILE_SECRET_KEY "$TURNSTILE_SECRET_KEY"
pause

# ── 6 ─────────────────────────────────────────────────────────────────────
stage "Web Analytics"
say "Počítá návštěvy bez cookies, takže web nepotřebuje cookie lištu."
echo
open_url "$DASH/web-analytics"
step "Add a site → v nabídce hostname vyber $DOMAIN → Done."
note "Automatic setup je zapnutý sám. Měřicí skript vloží Cloudflare do"
note "stránek, až bude web na doméně. Ověříme to v issue #10."
pause "Hotovo? Enter…"

# ── 7 ─────────────────────────────────────────────────────────────────────
stage "Přesměrování www.$DOMAIN → $DOMAIN"
say "Kdo napíše www.$DOMAIN, skončí na $DOMAIN, ať má web jednu adresu."
echo
open_url "$DASH/:zone/rules/overview"
step "Pokud se zeptá na doménu, vyber $DOMAIN."
step "Create rule → Redirect Rule."
step "Rule name: www to root"
step "If incoming requests match: Wildcard pattern."
step "Request URL: https://www.*"
step "Target URL: https://\${1}"
step "Status code: 301. Zaškrtni Preserve query string."
step "Deploy."
note "Začne fungovat po spuštění na doméně (poslední krok)."
pause "Hotovo? Enter…"

# ── 8 ─────────────────────────────────────────────────────────────────────
stage "Commit a náhled pull requestu"
say "Veřejný Site Key je v $ENV_FILE a build ho potřebuje, proto ho commitneme."
BRANCH="$(git branch --show-current)"
echo
if [[ "$BRANCH" == "master" ]]; then
  warn "Jsi na master. Přepni se na větev pull requestu a spusť wizard znovu."
  exit 1
fi
if git diff --quiet -- "$ENV_FILE" && git ls-files --error-unmatch "$ENV_FILE" >/dev/null 2>&1; then
  note "$ENV_FILE se nezměnil, není co commitovat."
elif confirm "Commitnout $ENV_FILE a pushnout větev $BRANCH?"; then
  git add "$ENV_FILE"
  git commit -m "Turnstile site key for production builds (#4)" >/dev/null
  git push >/dev/null 2>&1
  printf '  %s✓ pushnuto%s\n' "$GREEN" "$RESET"
else
  SKIPPED+=("commitnout a pushnout $ENV_FILE")
fi
PR_URL="$(gh pr view --json url -q .url 2>/dev/null || true)"
echo
if [[ -n "$PR_URL" ]]; then
  open_url "$PR_URL"
  say "Push spustil náhledový build. Cloudflare k pull requestu přidá komentář"
  say "se stavem buildu a odkazem na náhled (Preview URL)."
  step "Počkej na komentář a otevři Preview URL. Měl by se ukázat web."
else
  warn "K větvi $BRANCH jsem nenašel pull request; náhled zkontroluj v Cloudflare"
  warn "(Worker → Deployments)."
fi
if ! confirm "Náhled funguje?"; then
  SKIPPED+=("zkontrolovat náhled pull requestu (Enable Preview Builds v Settings → Build)")
fi

# ── 9 ─────────────────────────────────────────────────────────────────────
stage "Spuštění na $DOMAIN"
say "Merge pull requestu nasadí master. Ve wrangler.jsonc je teď doména"
say "$DOMAIN i www.$DOMAIN, takže si je Worker při nasazení připojí."
echo
[[ -n "$PR_URL" ]] && open_url "$PR_URL"
step "Zkontroluj, že CI je zelené, a dej Squash and merge."
step "V Cloudflare (Worker → Deployments) počkej na build z master."
pause "Build z master doběhl? Enter…"
echo
if wait_for_ok "https://$DOMAIN/en"; then
  say "Web běží na https://$DOMAIN přes HTTPS."
else
  warn "https://$DOMAIN/en zatím neodpovídá. Certifikát a DNS můžou chvíli trvat;"
  warn "zkus to za pár minut znovu, případně se podívej na build v Deployments."
  SKIPPED+=("ověřit, že https://$DOMAIN běží")
fi
WWW_STATUS="$(http_status "https://www.$DOMAIN/")"
if [[ "$WWW_STATUS" == "301" ]]; then
  printf '  %s✓ www.%s přesměrovává%s\n' "$GREEN" "$DOMAIN" "$RESET"
else
  warn "www.$DOMAIN vrací $WWW_STATUS místo 301. Zkontroluj pravidlo z kroku 7."
  SKIPPED+=("ověřit přesměrování www.$DOMAIN")
fi
pause

finish
(( ${#WORKER_SECRETS[@]} )) && note "tajemství ve Workeru $WORKER: ${WORKER_SECRETS[*]}"
printf '\n'
